apiVersion: v1
kind: Secret
metadata:
  name: port-io-secret
  labels:
    app.kubernetes.io/name: port-io
type: Opaque
stringData:
  oidc-client-secret: {{ .Values.port.auth.oidc.clientSecret | quote }}
  database-url: "postgresql://{{ .Values.port.database.username }}:{{ .Values.port.database.password }}@{{ .Values.port.database.host }}:{{ .Values.port.database.port }}/{{ .Values.port.database.database }}"
