apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app.kubernetes.io/name: keycloak
type: Opaque
stringData:
  admin-password: {{ .Values.keycloak.admin.password | quote }}
  db-password: {{ .Values.keycloak.database.password | quote }}
