apiVersion: cloudstack.terasky.com/v1alpha1
kind: VPC
metadata:
  name: my-vpc
spec:
  forProvider:
    name: "My VPC"
    cidr: "10.20.0.0/16"
    zone: "Homelab-Zone"
  providerConfigRef:
    name: default
